import { NextResponse } from 'next/server';
import { mongoDb } from '../../../lib/mongodb';
import { localStore } from '../../../lib/local-store';

const decline = 'Main sirf study-abroad information aur office ke approved university list ke baare mein guide karta hoon.';
export async function POST(request: Request) {
  const { phone, message } = await request.json().catch(() => ({}));
  if (!phone || !message) return NextResponse.json({ ok: false, message: 'Phone and message are required.' }, { status: 400 });
  try {
    const db = mongoDb(); const student = await db.collection('students').findOne({ phone_normalized: String(phone).replace(/\s/g, '') }) ?? await db.collection('students').findOne({ phone });
    const text = String(message).trim(); const lower = text.toLowerCase(); let reply = decline; let needsStaff = false;
    if (/ignore|accepted|accept me|rules/i.test(text)) reply = 'Main acceptance ka promise nahi kar sakta. Admission ka final decision university karti hai.';
    else { const university = await db.collection('universities').findOne({ $or: [{ university: { $regex: text, $options: 'i' } }, { program: { $regex: text, $options: 'i' } }] }); if (university) reply = `${university.university} — ${university.program}: fee ${university.fee}; deadline ${university.deadline}; minimum marks ${university.minMarks ?? university.min_marks}%; minimum IELTS ${university.minIelts ?? university.min_ielts}; documents: ${(university.documents ?? university.documents_needed ?? []).toString()}.`; else if (/university|college|program|fee|deadline|ielts|marks|document/i.test(lower)) { reply = 'Mujhe is university/program ki information approved list mein nahi milti. Main aapka question staff ko review ke liye bhej raha hoon.'; needsStaff = true; }}
    if (student) await db.collection('messages').insertOne({ student_id: student._id, student: student.name, sender: needsStaff ? 'student' : 'ai', message: text, response: reply, approval_status: needsStaff ? 'pending' : 'sent', needs_staff: needsStaff, created_at: new Date() });
    return NextResponse.json({ ok: true, reply, needsStaff, studentFound: Boolean(student) });
  } catch (error) { const student = localStore.students.find(s => (s.phone_normalized ?? String(s.phone).replace(/\s/g, '')) === String(phone).replace(/\s/g, '')); const text = String(message).trim(); const lower = text.toLowerCase(); let reply = decline; let needsStaff = false; if (/ignore|accepted|accept me|rules/i.test(text)) reply = 'Main acceptance ka promise nahi kar sakta. Admission ka final decision university karti hai.'; else { const university = localStore.universities.find(u => lower.includes(String(u.university).toLowerCase()) || lower.includes(String(u.program).toLowerCase())); if (university) reply = `${university.university} — ${university.program}: fee ${university.fee}; deadline ${university.deadline}; minimum marks ${university.minMarks}%; minimum IELTS ${university.minIelts}; documents: ${university.documents}.`; else if (/university|college|program|fee|deadline|ielts|marks|document/i.test(lower)) { reply = 'Mujhe is university/program ki information approved list mein nahi milti. Main aapka question staff ko review ke liye bhej raha hoon.'; needsStaff = true; } } if (student) localStore.messages.push({ id: `local-msg-${Date.now()}`, _id: `local-msg-${Date.now()}`, student: student.name, sender: needsStaff ? 'student' : 'ai', message: text, response: reply, approvalStatus: needsStaff ? 'pending' : 'sent', approval_status: needsStaff ? 'pending' : 'sent', needs_staff: needsStaff, created: 'Just now', created_at: new Date() }); return NextResponse.json({ ok: true, fallback: true, reply, needsStaff, studentFound: Boolean(student) }); }
}
