import Link from 'next/link';
import AppShell from '../components/AppShell';
import StatusBadge from '../components/StatusBadge';
import { getOfficeData } from '../lib/repository';
import { ArrowUpRight, Bot, FileCheck, ShieldCheck, Sparkles, Users, Zap } from 'lucide-react';

export default async function Dashboard() {
  const { students, universities, documents, messages, source } = await getOfficeData();
  const pending = messages.filter((m: any) => (m.approvalStatus ?? m.approval_status) === 'pending');
  return <AppShell><div className="mx-auto max-w-7xl">
    <section className="relative overflow-hidden rounded-[2rem] bg-ink px-6 py-9 text-white shadow-2xl md:px-10"><div className="orb -right-16 -top-24 h-72 w-72 bg-teal/60 blur-3xl"/><div className="relative"><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-3 py-1.5 text-xs font-semibold text-cyan-100"><Sparkles size={14}/> Agentic office control room</div><h1 className="max-w-2xl text-4xl font-black leading-tight md:text-5xl">Your study abroad office, <span className="text-cyan-300">always awake.</span></h1><p className="mt-5 max-w-2xl text-sm leading-7 text-slate-300">AI teammates welcome students, match programs, check documents and prepare follow-ups — while staff approve every message.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/approvals" className="inline-flex items-center gap-2 rounded-xl bg-cyan-300 px-4 py-3 text-sm font-bold text-ink">Open approval desk <ArrowUpRight size={16}/></Link><span className="inline-flex items-center gap-2 rounded-xl border border-white/15 bg-white/10 px-4 py-3 text-sm text-slate-200"><Bot size={16}/> {source === 'mongodb' ? 'MongoDB connected' : 'Demo fallback active'}</span></div></div></section>
    <div className="mt-4 rounded-xl border border-slate-200 bg-white px-4 py-3 text-xs text-slate-500">Data source: <strong className="text-ink">{source === 'mongodb' ? 'MongoDB' : 'Demo data'}</strong> · n8n approval gate is enabled</div>
    <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Students in pipeline" value={students.length} icon={<Users size={19}/>} /><Metric label="Human approvals" value={pending.length} icon={<ShieldCheck size={19}/>} /><Metric label="Programs in list" value={universities.length} icon={<Bot size={19}/>} /><Metric label="Documents to review" value={documents.filter((d: any) => (d.status ?? '') !== 'approved').length} icon={<FileCheck size={19}/>} /></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.1fr_.9fr]"><section className="rounded-2xl border border-slate-200 bg-white shadow-soft"><div className="flex items-center justify-between border-b border-slate-100 p-5"><div><h2 className="font-bold text-ink">Live student pipeline</h2><p className="mt-1 text-xs text-slate-500">MongoDB-backed staff view.</p></div><Link href="/students" className="text-sm font-semibold text-teal">View all</Link></div>{students.map((s: any) => <div key={String(s.id ?? s._id)} className="flex items-center justify-between gap-3 border-b border-slate-100 p-5 last:border-0"><div><p className="text-sm font-semibold">{s.name}</p><p className="mt-1 text-xs text-slate-500">{s.country} · {s.marks}% marks · IELTS {s.ielts ?? 'not taken'}</p></div><StatusBadge status={s.status === 'contacted' ? 'active' : (s.status ?? 'new')}/></div>)}</section><section className="rounded-2xl border border-amber-200 bg-amber-50/70 p-5"><div className="flex items-center justify-between"><div><h2 className="font-bold">Approval radar</h2><p className="mt-1 text-xs text-slate-600">No AI message leaves without a human.</p></div><Zap className="text-amber-700" size={21}/></div>{pending.length === 0 ? <p className="mt-5 text-sm text-slate-600">No pending messages.</p> : pending.map((m: any) => <div key={String(m.id ?? m._id)} className="mt-5 rounded-xl bg-white p-4 shadow-sm"><p className="text-sm font-bold">{m.student ?? 'Student'}</p><p className="mt-2 text-sm leading-6 text-slate-600">{m.message}</p><Link href="/approvals" className="mt-3 inline-block text-xs font-bold text-teal">Review message →</Link></div>)}</section></div>
  </div></AppShell>;
}
function Metric({ label, value, icon }: { label: string; value: number; icon: React.ReactNode }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-soft"><div className="flex items-start justify-between"><div><p className="text-xs text-slate-500">{label}</p><p className="mt-2 text-3xl font-black text-ink">{value}</p></div><div className="rounded-xl bg-cyan-50 p-3 text-teal">{icon}</div></div></div>; }
